language: go

go:
  - 1.9
  - tip

sudo: false

install:
  - curl -L -s https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.tar.gz | tar zxC ./
  - ./linux-amd64/glide install

script:
  - go test

after_script:
  ./test.sh
